# CodeRabbit Configuration for PineCMS
# Documentation: https://docs.coderabbit.ai/
# Plan: Lite ($12/mo)
# Last Updated: 2025-11-04

# Language & Tone
language: "en"
tone_instructions: |
  Be concise and professional. Focus on Laravel, Vue, and Inertia.js best practices.
  Prioritize security and performance. Follow Spatie Laravel Guidelines (.claude/spatie-laravel-guidelines.md).

# Review Settings
reviews:
  # Review aggressiveness: "chill" | "assertive"
  profile: "assertive"

  # Request changes workflow (blocks merge if critical issues)
  request_changes_workflow: false

  # Generate high-level summary
  high_level_summary: true

  # Add poem (fun, but not needed for serious projects)
  poem: false

  # Show review status
  review_status: true

  # Changed files summary (NEW 2024)
  changed_files_summary: true

  # Sequence diagrams for complex changes (NEW 2024)
  sequence_diagrams: true

  # Estimate code review effort (NEW 2024)
  estimate_code_review_effort: true

  # Assess linked issues (NEW 2024)
  assess_linked_issues: true

  # Auto-review on every commit
  auto_review:
    enabled: true
    # Review draft PRs for early feedback
    drafts: true

  # Note: SAST tools (PHPStan, ESLint, Semgrep) require Pro plan
  # Lite plan relies on CodeRabbit's built-in AI analysis

  # Path Filters (exclude generated/vendor files)
  path_filters:
    - "!vendor/**"
    - "!node_modules/**"
    - "!storage/**"
    - "!bootstrap/cache/**"
    - "!public/build/**"
    - "!coverage/**"
    - "!*.min.js"
    - "!*.min.css"

  # Review Scope
  path_instructions:
    - path: "app/Models/**"
      instructions: |
        Focus on:
        - Eloquent relationships with proper return types
        - N+1 query prevention (eager loading)
        - Mass assignment protection ($fillable/$guarded)
        - Database indexes for foreign keys

    - path: "app/Http/Controllers/**"
      instructions: |
        Focus on:
        - FormRequest validation classes (not inline validation)
        - Proper authorization (gates/policies)
        - Service layer usage (no business logic in controllers)
        - Type hints for all methods

    - path: "app/Services/**"
      instructions: |
        Focus on:
        - Single Responsibility Principle
        - Event dispatching for side effects
        - DTO usage for data transfer
        - Exception handling

    - path: "resources/js/**"
      instructions: |
        Focus on:
        - Vue 3 Composition API best practices
        - Inertia.js form handling
        - TypeScript type safety
        - Component reusability

    - path: "tests/**"
      instructions: |
        Focus on:
        - Test coverage for happy paths and edge cases
        - Factory usage for model creation
        - Proper assertions
        - Database transaction rollbacks

    - path: "database/migrations/**"
      instructions: |
        Focus on:
        - Down method implementation
        - Foreign key constraints
        - Indexes for query optimization
        - Data type appropriateness

    - path: ".claude/**"
      instructions: |
        Focus on:
        - Documentation clarity and accuracy
        - Consistency with other guidelines
        - Markdown formatting
        - No duplication with root CLAUDE.md

    - path: "docs/**"
      instructions: |
        Focus on:
        - Technical accuracy
        - Code examples validity
        - Markdown best practices
        - Links to official documentation

# Chat Settings
chat:
  # Auto-reply to comments
  auto_reply: true

  # Commands available:
  # @coderabbitai help - Show available commands
  # @coderabbitai review - Re-review current PR
  # @coderabbitai ask <question> - Ask specific question about code

# Knowledge Base (NEW 2024/2025)
knowledge_base:
  # Enable learning from past reviews
  learnings:
    scope: "auto"  # Learn from this repo

  # Code Guidelines Integration (CRITICAL for PineCMS!)
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"  # Main AI guidelines (root)
      - "**/.claude/CLAUDE.md"  # PineCMS-specific guidelines
      - "**/.claude/spatie-laravel-guidelines.md"  # Industry standard Laravel conventions
      - "**/.cursorrules"  # Alternative AI guidelines
      - "**/docs/CONTRIBUTING.md"  # Contribution guidelines

# Plan Configuration
# Lite plan features enabled:
# ✓ Unlimited PR reviews
# ✓ Customizable Learnings (knowledge_base)
# ✓ Real-time Web Query
# ✓ Code Graph Analysis
# ✓ Reviews in IDE
#
# Pro-only features (disabled):
# ✗ SAST tools integration (PHPStan, ESLint, Semgrep)
# ✗ Jira & Linear integration
# ✗ Agentic Chat
# ✗ Analytics dashboards
# ✗ Docstrings generation
